[project]
name = "pythonproject1"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "djangorestframework-simplejwt (>=5.4.0,<6.0.0)",
    "django (>=5.1.6,<6.0.0)",
    "pytelegrambotapi (>=4.26.0,<5.0.0)",
    "ngrok (>=1.4.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"