# Generated by Django 4.2.13 on 2024-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_average_time_result_average_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='average_time',
            field=models.FloatField(default=0.0),
        ),
    ]
