# Generated by Django 4.2.13 on 2024-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_rename_attempt_count_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingTestText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
    ]
