# Generated by Django 4.2.13 on 2024-06-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_typingtesttext_remove_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingtesttext',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
